# Generated by Django 2.1.3 on 2019-07-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='twitter_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
